// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYlNfgNYZ9JpaaKnB7jCYAa3cN4DA7doQ',
    appId: '1:289612693571:web:d47abc6a533d3094f414f6',
    messagingSenderId: '289612693571',
    projectId: 'digipal-97c66',
    authDomain: 'digipal-97c66.firebaseapp.com',
    storageBucket: 'digipal-97c66.firebasestorage.app',
    measurementId: 'G-KVQYY3QYXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bC41NjJbOxGD4O8l0XITDOMxPEuSef8',
    appId: '1:289612693571:android:2024d4e6d12d107ef414f6',
    messagingSenderId: '289612693571',
    projectId: 'digipal-97c66',
    storageBucket: 'digipal-97c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE4fNAh1PgmeQ9VFbEKvAlXrgtzqpU6x0',
    appId: '1:289612693571:ios:9f49519464958539f414f6',
    messagingSenderId: '289612693571',
    projectId: 'digipal-97c66',
    storageBucket: 'digipal-97c66.firebasestorage.app',
    iosBundleId: 'com.example.digipal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE4fNAh1PgmeQ9VFbEKvAlXrgtzqpU6x0',
    appId: '1:289612693571:ios:9f49519464958539f414f6',
    messagingSenderId: '289612693571',
    projectId: 'digipal-97c66',
    storageBucket: 'digipal-97c66.firebasestorage.app',
    iosBundleId: 'com.example.digipal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYlNfgNYZ9JpaaKnB7jCYAa3cN4DA7doQ',
    appId: '1:289612693571:web:00a69a0a35ce7dacf414f6',
    messagingSenderId: '289612693571',
    projectId: 'digipal-97c66',
    authDomain: 'digipal-97c66.firebaseapp.com',
    storageBucket: 'digipal-97c66.firebasestorage.app',
    measurementId: 'G-0G526135R5',
  );
}
